### ISSUE TITLE
Release v0.7

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-connectivity#181]
A lot of new features courtesy of @tsbinns.

We should aim to make a release. @tsbinns any interest in trying this out?

**Comment by tsbinns** [comment]
@adam2392 Sorry for the delay, I was on holiday the last 2 weeks.

Yes, I would be very interested!

**Comment by adam2392** [comment]
Would a v0.7 release of current code be better before merging in any GSoC changes? 

linking: https://github.com/mne-tools/mne-connectivity/issues/183

I'm okay either way I suppose. cc: @drammock

**Comment by drammock** [comment]
seems worth cutting a release now --- not necessarily because of impending GSoC changes, but because it's been ~5 months and there are some useful changes and bugfixes on `main`.

**Comment by tsbinns** [comment]
@adam2392 I'm happy to help out if the offer still stands!

**Comment by adam2392** [comment]
I don't have a walk-thru of how to do this exactly for mne-connectivity, but mne-bids has a writeup on how to do this. We just don't have a few of their steps tho.

https://github.com/mne-tools/mne-bids/wiki/How-to-make-a-release

Do you want to take a look and see if you can sketch out a sequence of steps that makes sense to you? Once you do it once, you'll have the exp to do it on any package :)

**Comment by adam2392** [comment]
Let us know if you have questions

**Comment by tsbinns** [comment]
Sounds good, I will try and get this done ASAP.

Though it might be worth waiting until #184 is merged since this has some nice efficiency improvements and is unrelated to the GSoC work. Thoughts?

**Comment by adam2392** [comment]
Sounds good to me!

**Comment by tsbinns** [comment]
WIP in #195

**Comment by drammock** [comment]
> @adam2392 One of the steps mentioned in the wiki is uploading to and checking install from test-pypi, but I don't have access. Do you need to do this before moving forward, or is it good enough that the installation in the circleci passes?

Been a while since I've done this so I just tried and:

- @adam2392 and @larsoner are the only maintainers on PyPI for mne_connectivity, so I can't help
- the process is: create an account on test.pypi.org (requires setting up 2FA)
- generate an API token through account settings
- run the `twine upload...` command and at the username prompt enter `__token__` and at the password prompt enter the API token.  https://test.pypi.org/help/#apitoken

**Comment by larsoner** [comment]
Rather than do all that I'd rather modernize with trusted artifact publishing on release

https://github.com/pypa/gh-action-pypi-publish?tab=readme-ov-file#usage

Can start from this and remove the username password stuff, then I can configure trusted publishing on PyPI:

https://github.com/mne-tools/mne-bids-pipeline/blob/main/.github/workflows/release.yml

@tsbinns if you want to learn how to do CI stuff feel free to open a PR to get the ball rolling. I can do the (pretty easy) config at the PyPI end of things. If you would rather focus on moving on to connectivity I can set up the action instead.

**Comment by adam2392** [comment]
Sorry for the delay. I had my wedding this past weekend so life was hectic. 

But I agree that a GH action might make more sense and prevent this workflow issue in the future.

**Comment by larsoner** [comment]
> Sorry for the delay. I had my wedding this past weekend so life was hectic.

Awesome congrats! 🎉 

Whenever convenient if you could make me an owner rather than maintainer I can do the trusted publishing stuff:

https://pypi.org/project/mne-connectivity/

You can also do it if you want (but please do make me an owner either way, it's not recommended to have a single owner of a project):

https://docs.pypi.org/trusted-publishers/adding-a-publisher/

**Comment by tsbinns** [comment]
Congrats @adam2392!

<br>

> @tsbinns if you want to learn how to do CI stuff feel free to open a PR to get the ball rolling. I can do the (pretty easy) config at the PyPI end of things. If you would rather focus on moving on to connectivity I can set up the action instead.

@larsoner Definitely, would be happy to try this. Will open a PR soon.

**Comment by tsbinns** [comment]
@larsoner Do you want me to create a new maint/0.7 branch and update the built docs in the gh-pages branch?

**Comment by adam2392** [comment]
@larsoner sorry for the delay! Added you as an owner now.

**Comment by larsoner** [comment]
> @larsoner Do you want me to create a new maint/0.7 branch and update the built docs in the gh-pages branch?

I wasn't sure if you had permissions so I went ahead and did these steps. In theory CircleCI should try to push 0.7 to https://mne.tools/mne-connectivity/stable soon!
