### ISSUE TITLE
[BUG] Enable averaging connectivity over tapers instead of averaging PSD over tapers

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-connectivity#84]
As of v1.0 MNE-Python, there was a bug fix to not average the `tfr` in multitaper analysis unless the user specified. So using that in mne-connectivity, we need to compute the power in multiple tapers, and then compute connectivity and then average across tapers.

I see. Thanks for this comment. Perhaps that is why there are some issues in #73

_Originally posted by @adam2392 in https://github.com/mne-tools/mne-connectivity/pull/82#discussion_r805027992_

**Comment by adam2392** [comment]
@Div12345 and @avoide 

https://github.com/mne-tools/mne-connectivity/blob/711ccce68545c14dd9aab40213efe3e1f06e18cf/mne_connectivity/spectral/time.py#L269-L282

These lines possibly are contributing to the discrepancy we see. Before, we were averaging multi taper analysis across tapers before we computed connectivity. We should instead be computing connectivity for all tapers and then averaging.

**Comment by Div12345** [comment]
@adam2392  Is there a regression test that already covers this? Because I commented out 276,277 and uncommented 281,282 and all tests seem to pass.. If not, I could try writing a regression test and checking it out..

**Comment by adam2392** [comment]
No unfortunately there is not. The issue that made it not a "trivial fix" is that the conn_func needs to be applied for each taper, but right now the API doesn't support doing something like that.

I would first identify what pieces of code need to change and propose a quick pseudocode here to see if it makes sense.

**Comment by ruuskas** [comment]
I'm currently working on this issue and probably have already solved it, barring testing.

**Comment by adam2392** [comment]
Sure sounds good! @ruuskas lmk if there's a PR you would like help iterating on. I can suggest help for testing if needed.

**Comment by ruuskas** [comment]
Sure, I would like some help with the upcoming PR. I'm in the process of making the API more similar to `spectral_connectivity_epochs` and also fixed the issue with PLV computation, mentioned in #90 and #73.

**Comment by adam2392** [comment]
Awesome excited to see the PR! Feel free to start it early as a "WIP" Draft.

**Comment by ruuskas** [comment]
@adam2392 I have submitted the PR. Could you have a look when you have time?

**Comment by ruuskas** [comment]
Hi @adam2392, @larsoner. I came back to this after finding some quite peculiar behaviour with the connectivity function. Are you sure that this conclusion is correct:
```
 # TODO: This is wrong -- it averages in the complex domain (over tapers). 
 # What it *should* do is compute the conn for each taper, then average 
 # (see below). 
```

I did some testing with this, and the connectivity results do not appear smooth at all. See plots below. Most importantly, there's a dip in connectivity at 10Hz, which is the only actual coupling frequency in the simulated data. Morlet convolution for comparison.

![multitaper_plv_10hz](https://user-images.githubusercontent.com/66060772/200384343-1cbb186e-34f4-4760-8883-dd7602d4515c.png)

![morlet_10Hz_plv](https://user-images.githubusercontent.com/66060772/200384337-dc9e8886-335a-4c5f-bcfc-ee65e1a22134.png)

These were computed with the implementation found in #104.

I'm just guessing, but perhaps the cross-spectral density should be averaged and connectivity computed from that instead of averaging connectivity matrices? I will go through the code tomorrow to check for other potential bugs.

**Comment by larsoner** [comment]
> Are you sure that this conclusion is correct:

In principle yes it seems like a reasonable conclusion to me.

I agree that the first plot looks buggy, though -- I wouldn't expect it to look like that. Have you tried using multitaper with exactly one taper? That should look more like the `morlet` case. Then I'd try with one taper again, but this time just using the *second* taper instead of the first. (This will be a pain to code potentially but it should be doable.) Both of these should be smooth, similar to the Morlet case. If they are, the aggregate should also be smooth. From there you could use exactly two tapers (first and second) and see that the result is smooth. If it isn't, then it seems like there is some bug in the code that combines these values. If it is smooth, I'd gradually increase the number of tapers until I started seeing problems, then try to understand why they arise...

**Comment by ruuskas** [comment]
Hi @larsoner. I tried doing what you suggested. Indeed, the second taper is not smooth, nor is the third.
![multitaper-2tapers-first-only](https://user-images.githubusercontent.com/66060772/200569609-68e7f54b-b39c-4cf4-b09e-47f93950ec17.png)
![multitaper-2tapers-second-only](https://user-images.githubusercontent.com/66060772/200569618-62e180be-1cc6-4fed-8d77-e6114bd7fff5.png)
![multitaper-3tapers-third-only](https://user-images.githubusercontent.com/66060772/200570437-7edfb9bf-8490-48d6-8426-06e6746555e1.png)


I also plotted the CSD computed from the output of `tfr_array_multitaper` with `output='complex'`. It looks like the tapered signal doesn't have spectral content at 10Hz, which means that there cannot be connectivity either.

![csd_for_tapers](https://user-images.githubusercontent.com/66060772/200570219-80e8e976-6a73-48e1-b1d4-40ad021704eb.png)

The simulated data in this case is a 10Hz sinusoid with amplitude 0.3 and random but constant phase in each channel, with uniformly random additive noise.

**Comment by ruuskas** [comment]
Hi @larsoner, @adam2392!

Here's a comparison between the three different ways to average the tapers. Namely, averaging connectivity matrices, averaging the complex signal, and averaging the CSD. I plotted five different connectivity metrics against frequency. The underlying signal in the simulated channels is a 10Hz phase-locked sinusoid with additive noise. 

It looks like averaging the CSD would give the smoothest result. This conclusion appears to be supported by the formulation [in Wikipedia](https://en.wikipedia.org/wiki/Multitaper). WDYT?

![multitaper_taper_averaging](https://user-images.githubusercontent.com/66060772/200611063-9caec73d-1213-4b96-8c46-e9a754af6a6d.png)

**Comment by larsoner** [comment]
In the "average connectivity" case, is it a weighted average? I think it needs to be in order to be comparable. A naive/simple average would unfairly bias the results to the tapes with less power compared to the average-complex and average-CSD cases (which implicitly include the weighting IIUC).

**Comment by larsoner** [comment]
... but in any case, from thinking about it briefly it seems like the CSD case could very well in principle be the best choice. Any spectral modification imposed by the window function will occur on both the X and Y signals, but this should go away during CSD computation because it effectively only looks at *relative* amplitude and phase (compared to the average-complex-signals case where any phase shifts across tapers will be combined/averaged rather than removed before averaging).

And as you point out this quote makes it clear:

> The multitaper cross-spectral estimator between channel l and m is the average of K direct cross-spectral estimators between the same pair of channels (l and m)

So +1 for using averaged PSD. I'm still curious about the weighted vs unweighted average in the above plots, but even if these are unweighted, I'm guessing the weighted average will not look as reasonable (or be as correct in principle!) as the average CSD case.

**Comment by ruuskas** [comment]
> @ruuskas can you plot the tapers themselves to see if they look right? I would expect something like this (blue, orange, green are the first 3):
> 
> ![Screenshot 2022-11-08 at 10-17-31 lab - JupyterLab](https://user-images.githubusercontent.com/1810515/200618630-d9096070-0bd5-4f5f-b810-4e75d57c7e62.png)

Not easily, but [that part](https://github.com/mne-tools/mne-python/blob/f26528d78764c83f754873c40f17e40d5eb08d2d/mne/time_frequency/multitaper.py#L12) is inside `mne.time_frequency.tfr_array_multitaper` so I would assume it to be correct.

**Comment by ruuskas** [comment]
> In the "average connectivity" case, is it a weighted average? I think it needs to be in order to be comparable. A naive/simple average would unfairly bias the results to the tapes with less power compared to the average-complex and average-CSD cases (which implicitly include the weighting IIUC).

This was just the simple average without any weighting. How should one go about computing the weights? I would assume that the weights should be frequency specific.

> So +1 for using averaged PSD. I'm still curious about the weighted vs unweighted average in the above plots, but even if these are unweighted, I'm guessing the weighted average will not look as reasonable (or be as correct in principle!) as the average CSD case.

I see. I could add this in the PR where I'm already suggesting several changes to `spectral_connectivity_time`.

**Comment by larsoner** [comment]
> I would assume that the weights should be frequency specific.

Usually taper-specific. They are related to the eigenvalues from the eigen decomp that computes the tapers, see for example

https://github.com/mne-tools/mne-python/blob/f26528d78764c83f754873c40f17e40d5eb08d2d/mne/time_frequency/multitaper.py#L128

We should already use them in MNE-Python when computing PSDs. In addition to potentially being useful for your comparison above, we should probably use them when averaging the CSDs across tapers just like we do for PSDs.

**Comment by ruuskas** [comment]
> Usually taper-specific. They are related to the eigenvalues from the eigen decomp that computes the tapers, see for example
>
> We should already use them in MNE-Python when computing PSDs. In addition to potentially being useful for your comparison above, we should probably use them when averaging the CSDs across tapers just like we do for PSDs.

Just to be sure we're on the same page, the results above were computed using the complex signal output from `tfr_array_multitaper`, not using the CSD function `csd_array_multitaper` from MNE-Python. Do you think the weighting should be applied to the output of  `tfr_array_multitaper`?

**Comment by larsoner** [comment]
I think any time you combine estimates from multiple tapers, you probably want to use a weighted average rather than a naive/uniform average. So assuming your `tfr_array_multitaper` returns estimates at the level of individual tapers, once you go to combine them (later) at the CSD stage, it seems like you should use the same weights that we use when computing a PSD.

**Comment by ruuskas** [comment]
Here is the figure including the weighted average of CSD. The weights are very close to one, rendering their effect miniscule.
The code is [here](https://github.com/ruuskas/mne-connectivity/blob/a5db88b0a98bd263aac7ff8a0649871779dceca8/mne_connectivity/spectral/time.py#L425).

![multitaper_taper_averaging](https://user-images.githubusercontent.com/66060772/201066153-9c146bb4-4327-4228-8b19-0c22f74d734a.png)

**Comment by larsoner** [comment]
+1 for using the weighted average since I think in principle it's more correct, and consistent with how we do PSDs
